spring:
  application:
    name: file-upload

---

spring:
  profiles:
    active: local
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      enabled: false
      fail-fast: true