server:
  port: 8080

spring:
  application:
    name: file-upload
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      groupId: file-upload-id
file-status-processor-url: ${FILE_STATUS_PROCESSOR_URL}